name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: npm ci
      run: |
        npm ci

    - name: npm run-script lint
      run: |
        npm run-script lint

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm run-script test
      run: |
        npm run-script test